version: "2"
linters:
  default: standard
  enable:
    - gocritic
    - gosec
    - errorlint
    - revive
    - misspell
    - unconvert
    - unparam
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    presets:
      - common-false-positives
